# Generated by Django 3.1.7 on 2021-03-20 01:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAkun',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_petugas',
            },
        ),
        migrations.CreateModel(
            name='Spp',
            fields=[
                ('id_spp', models.AutoField(primary_key=True, serialize=False)),
                ('tahun', models.IntegerField(blank=True)),
                ('bulan', models.IntegerField(blank=True)),
                ('nominal', models.IntegerField(blank=True)),
                ('petugas', models.ForeignKey(default='', on_delete=models.SET(''), to='mokletspp_backend.petugas')),
            ],
            options={
                'db_table': 'tb_spp',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nisn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nis', models.CharField(blank=True, max_length=255)),
                ('nama_siswa', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_siswa',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_bayar', models.DateTimeField(auto_now=True)),
                ('jumlah_bayar', models.IntegerField(blank=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('bukti_bayar', models.FileField(blank=True, upload_to='assets/upload/')),
                ('siswa', models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='mokletspp_backend.siswa')),
                ('spp', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='mokletspp_backend.spp')),
            ],
            options={
                'db_table': 'tb_pembayaran',
            },
        ),
    ]
